# Ваш уникальный API-ключ. Telegram @Fronzter Website www.mind-ai.tech
api-key: "key-ai"

api-endpoints:
  license-server: "http://license.mind-ai.tech"
  analysis-server: "http://api.mind-ai.tech"

# Настройки модуля машинного обучения (ML)
ml-check:
  enabled: true
  frames-to-analyze: 150 # Не менять!
  # Порог уверенности. Рекомендуется 0.80-0.95 для уменьшения ложных срабатываний.
  classification-threshold: 0.80

  # Сколько VL добавляется за один флаг от античита.
  vl-increment: 0.5

  # Порог VL, при достижении которого игрок будет наказан.
  violation-threshold: 2

  # Время жизни одного флага в секундах.
  # Через это время 1 флаг (vl-increment) полностью исчезнет. (600 = 10 минут)
  # VL будет уменьшаться постепенно в течение этого времени.
  window: 600

# Настройки оповещений для администрации
alerts:
  enabled: true
  permission: "mindai.alerts"
  # Формат сообщения. %vl% теперь будет показывать текущий VL и порог (например, 6.6/7) раньше было обычно 1/1 типо
  message: "&8[&3MindAI&8] &f%player% &bподозревается в читерстве &8(&3%probability% | VL: %vl%&8)"

# АВТОМАТИЧЕСКОЕ НАКАЗАНИЕ (при достижении VL)
auto-punishment:
  # Режим автоматического наказания: INSTANT, ANIMATED, ALERTS_ONLY
  # INSTANT это без анимки бан ANIMATED анимка ALERTS_ONLY просто алерты
  mode: INSTANT
  # Команда, которая будет выполнена, если выбран режим INSTANT
  command: "ban %player% Ваш аккаунт был заблокирован системой MindAi за нарушение правил."

# АНИМАЦИЯ НАКАЗАНИЯ (для /mindai punish и режима ANIMATED)
punishment-animation:
  enabled: true
  duration: 5
  levitation-strength: 1
  particle:
    type: REDSTONE
    color: ORANGE
    size: 1.0
    radius: 1.5
    count: 10
  sounds:
    start-sound: ENTITY_EVOKER_PREPARE_SUMMON
    end-sound: ENTITY_WITHER_DEATH
  # Команда, которая будет выполнена В КОНЦЕ АНИМАЦИИ
  command: "kick %player% &fВы были изгнаны силой эй ай"