api-key: "Ключ" # Получить @Fronzter telegram или mind-ai.tech (сайт)

api-endpoints:
  license-server: "http://license.mind-ai.tech"
  analysis-server: "http://api.mind-ai.tech"
ml-check:
  enabled: true
  frames-to-analyze: 150 # Не менять иначе 0 детекта будет!
  classification-threshold: 0.80
  violation-threshold: 3
  window: 600
alerts:
  enabled: true
  permission: "mindai.alerts"
  message: "&8[&3MindAI&8] &f%player% &bподозревается в читерстве &8(&3%probability%&8)"
  violation-command: "kick %player% cheat"
  punishment: "kick %player% cheat"