name: MindAI
version: 1.0
main: ru.Fronzter.MindAc.MindAI
api-version: 1.13
author: Fronzter
website: www.mind-ai.tech
permissions:
  mindai.alerts:
    default: op
  mindai.admin:
    default: op

commands:
  mindai:
    aliases: [mac]
    permission: mindai.admin
    usage: "/<command> [reload|alerts|history|punish]"