name: MindAI
version: 1.0
main: ru.Fronzter.MindAc.MindAI
api-version: 1.13
author: Fronzter
permissions:
  mindai.alerts:
    description: Разрешает получать оповещения от системы анализа
    default: op